import React, { useState, useEffect } from 'react';
import {
    Box, Typography, Paper, Table, TableBody, TableCell, TableContainer,
    TableHead, TableRow, IconButton, Chip, Tooltip, Dialog, DialogTitle,
    DialogContent, DialogActions, Button
} from '@mui/material';
import { Delete, Lock, LockOpen, Warning, DeleteForever } from '@mui/icons-material';
import PageHeader from '../../components/common/PageHeader';
import axios from '../../api/axios';
import { toast } from 'sonner';
import { QRCodeSVG } from 'qrcode.react';

const ManageQR = () => {
    const [links, setLinks] = useState([]);
    const [deleteModal, setDeleteModal] = useState({ open: false, type: '', id: null });

    const fetchLinks = async () => {
        try {
            const res = await axios.get('/api/utilities/admin/all');
            const qrUrls = res.data.data.filter(item => item.type === 'qr');
            setLinks(qrUrls);
        } catch (error) {
            toast.error('Failed to fetch QR codes');
        }
    };

    useEffect(() => {
        fetchLinks();
    }, []);

    const handleToggleStatus = async (id) => {
        try {
            await axios.put(`/api/utilities/admin/${id}/status`);
            toast.success('Status updated');
            fetchLinks();
        } catch (error) {
            toast.error('Failed to update status');
        }
    };

    const handleDelete = async () => {
        try {
            if (deleteModal.type === 'soft') {
                await axios.delete(`/api/utilities/admin/${deleteModal.id}/soft-delete`);
                toast.success('Soft deleted successfully');
            } else if (deleteModal.type === 'hard') {
                await axios.delete(`/api/utilities/admin/${deleteModal.id}/hard-delete`);
                toast.success('Hard deleted successfully');
            }
            setDeleteModal({ open: false, type: '', id: null });
            fetchLinks();
        } catch (error) {
            toast.error(`Failed to ${deleteModal.type} delete`);
        }
    };

    return (
        <Box>
            <PageHeader title="Manage QR Codes" subtitle="Admin panel to manage all generated QR codes" />

            <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", mb: 3, mt: 3, px: 3 }}>
                <Typography variant="h6" sx={{ color: "var(--text-primary)", fontWeight: 800 }}>
                    All QR Codes
                </Typography>
            </Box>

            <Box sx={{ px: 3, pb: 3 }}>
                {links.length === 0 ? (
                    <Box sx={{
                        display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
                        py: 8, px: 3, background: "var(--bg-panel)", borderRadius: "16px",
                        border: "1px dashed var(--border-color)", boxShadow: "var(--shadow-premium)", textAlign: "center"
                    }}>
                        <Typography variant="h6" sx={{ color: "var(--text-secondary)", fontWeight: 600, mb: 1 }}>
                            No QR Codes Found
                        </Typography>
                        <Typography variant="body2" sx={{ color: "text.secondary", mb: 3, maxWidth: "400px" }}>
                            There are currently no QR codes generated by any user.
                        </Typography>
                    </Box>
                ) : (
                    <TableContainer component={Paper} sx={{ borderRadius: "16px", background: "var(--bg-panel)", border: "1px solid var(--border-color)", boxShadow: "var(--shadow-premium)", overflowX: "auto" }}>
                        <Table sx={{ minWidth: 800 }}>
                            <TableHead sx={{ background: "var(--gradient-primary)" }}>
                                <TableRow>
                                    <TableCell sx={{ fontWeight: 700, color: "#fff", py: 2 }}>Creator</TableCell>
                                    <TableCell sx={{ fontWeight: 700, color: "#fff", py: 2 }}>Original URL</TableCell>
                                    <TableCell sx={{ fontWeight: 700, color: "#fff", py: 2 }}>QR Preview</TableCell>
                                    <TableCell sx={{ fontWeight: 700, color: "#fff", py: 2 }}>Clicks</TableCell>
                                    <TableCell sx={{ fontWeight: 700, color: "#fff", py: 2 }}>Status</TableCell>
                                    <TableCell sx={{ fontWeight: 700, color: "#fff", py: 2, textAlign: 'right' }}>Actions</TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                {links.map((link) => (
                                    <TableRow key={link._id} sx={{ "&:hover": { background: "var(--bg-accent-1)" }, transition: "background 0.15s", opacity: link.isDeleted ? 0.5 : 1 }}>
                                        <TableCell>
                                            <Typography variant="body2" fontWeight="bold" sx={{ color: "var(--text-primary)" }}>
                                                {link.userId?.name || 'Unknown'}
                                            </Typography>
                                            <Typography variant="caption" sx={{ color: "var(--text-secondary)", display: "block" }}>
                                                {link.userId?.designation || ''} | ID: {link.userId?.employeeId || ''}
                                            </Typography>
                                        </TableCell>
                                        <TableCell sx={{ maxWidth: '200px', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                                            {link.longUrl}
                                        </TableCell>
                                        <TableCell>
                                            <QRCodeSVG 
                                                value={`${import.meta.env.VITE_API_BASE_URL || 'http://localhost:9000/api'}/utilities/r/${link.shortCode}`} 
                                                size={40} 
                                            />
                                        </TableCell>
                                    <TableCell>{link.clicks}</TableCell>
                                    <TableCell>
                                        {link.isDeleted ? (
                                            <Chip label="Deleted" color="error" size="small" />
                                        ) : link.isActive ? (
                                            <Chip label="Active" color="success" size="small" />
                                        ) : (
                                            <Chip label="Inactive" color="warning" size="small" />
                                        )}
                                    </TableCell>
                                    <TableCell align="right">
                                        {!link.isDeleted && (
                                            <Tooltip title={link.isActive ? "Deactivate" : "Activate"}>
                                                <IconButton onClick={() => handleToggleStatus(link._id)} size="small" color={link.isActive ? "warning" : "success"}>
                                                    {link.isActive ? <Lock fontSize="small" /> : <LockOpen fontSize="small" />}
                                                </IconButton>
                                            </Tooltip>
                                        )}
                                        {!link.isDeleted && (
                                            <Tooltip title="Soft Delete">
                                                <IconButton onClick={() => setDeleteModal({ open: true, type: 'soft', id: link._id })} size="small" color="error">
                                                    <Delete fontSize="small" />
                                                </IconButton>
                                            </Tooltip>
                                        )}
                                        <Tooltip title="Hard Delete">
                                            <IconButton onClick={() => setDeleteModal({ open: true, type: 'hard', id: link._id })} size="small" sx={{ color: '#d32f2f' }}>
                                                <DeleteForever fontSize="small" />
                                            </IconButton>
                                        </Tooltip>
                                    </TableCell>
                                </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </TableContainer>
                )}
            </Box>

            {/* Delete Confirmation Modal */}
            <Dialog open={deleteModal.open} onClose={() => setDeleteModal({ open: false, type: '', id: null })}>
                <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1, color: '#d32f2f' }}>
                    <Warning /> Confirm {deleteModal.type === 'hard' ? 'Hard Delete' : 'Soft Delete'}
                </DialogTitle>
                <DialogContent>
                    <Typography>
                        {deleteModal.type === 'hard' 
                            ? 'Are you sure you want to permanently delete this QR code? This action cannot be undone.'
                            : 'Are you sure you want to soft delete this QR code? It will be marked as deleted and inactive.'
                        }
                    </Typography>
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setDeleteModal({ open: false, type: '', id: null })}>Cancel</Button>
                    <Button onClick={handleDelete} color="error" variant="contained">Confirm</Button>
                </DialogActions>
            </Dialog>
        </Box>
    );
};

export default ManageQR;
